### ISSUE TITLE
Attribution error upon calling upload_project

### ISSUE THREAD

**Issue by mwakok** [mwakok/ghproject#8]
Problem occurs in the argument parser:

```bash
$ python -m ghproject.upload_project -h
Traceback (most recent call last):
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\site-packages\ghproject\upload_project.py", line 31, in <module>
    args = create_parser()
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\site-packages\ghproject\arg_parser.py", line 54, in create_parser
    args = parser.parse_args()
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 1044, in __call__
    parser.print_help()
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 2494, in print_help
    self._print_message(self.format_help(), file)
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 2471, in format_help
    formatter.add_arguments(action_group._group_actions)
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 276, in add_arguments
    self.add_argument(action)
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 261, in add_argument
    invocations = [get_invocation(action)]
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 563, in _format_action_invocation
    default = self._get_default_metavar_for_optional(action)
  File "C:\Users\Maurits\miniconda3\envs\env_test\lib\argparse.py", line 705, in _get_default_metavar_for_optional
    return action.type.__name__
AttributeError: 'NoneType' object has no attribute '__name__'
```

**Comment by mwakok** [comment]
Problem was caused by a missing type parameter for the argument "--columns". Resolved with 65cd13177605ab6eded6457e399070370b04d041
